config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :passengers
  resources :flights
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "flights#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure, class_name: "Airport"
  belongs_to :arrival, class_name: "Airport"

  has_many :bookings
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [ :show, :edit, :update, :destroy ]

  # GET /flights or /flights.json
  def index
    @airport_options = Airport.all.map{ |airport| [airport.code, airport.id] }

    Rails.logger.debug "Flight params: #{flight_params.inspect}"
    date = get_date
    Rails.logger.debug "Parsed date: #{date}"

    @seats = flight_params["seats"]

    @flights = Flight.where(departure_id: flight_params["departure_id"])
    .where(arrival_id: flight_params["arrival_id"])
    .where("DATE(date) = ?", date)
    .where("vacancy >= ?", flight_params[:seats].to_i)

    Rails.logger.debug "Generated SQL: #{@flights.to_sql}"
    Rails.logger.debug "Result count: #{@flights.count}"
  end

  # GET /flights/1 or /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: "Flight was successfully created." }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: "Flight was successfully updated." }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy!

    respond_to do |format|
      format.html { redirect_to flights_path, status: :see_other, notice: "Flight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.permit(:name, :departure_id, :arrival_id, :seats, :commit, :date => {})
    end

    def get_date
      date_params = flight_params[:date]
      if date_params && date_params[:year] && date_params[:month] && date_params[:day]
        Date.new(date_params[:year].to_i, date_params[:month].to_i, date_params[:day].to_i)
      else
        nil
      end
    rescue ArgumentError => e
      Rails.logger.debug "Error parsing date: #{e.message}"
      nil
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_flight.html.erb
<div id="<%= dom_id flight %>">
  <p>
    <strong>Date:</strong>
    <%= flight.date %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= flight.name %>
  </p>

  <p>
    <strong>Departure:</strong>
    <%= flight.departure_id %>
  </p>

  <p>
    <strong>Arrival:</strong>
    <%= flight.arrival_id %>
  </p>

  <p>
    <strong>Vacancy:</strong>
    <%= flight.vacancy %>
  </p>

</div>

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :departure_id, style: "display: block" %>
    <%= form.text_field :departure_id %>
  </div>

  <div>
    <%= form.label :arrival_id, style: "display: block" %>
    <%= form.text_field :arrival_id %>
  </div>

  <div>
    <%= form.label :vacancy, style: "display: block" %>
    <%= form.number_field :vacancy %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<% content_for :title, "Editing flight" %>

<h1>Editing flight</h1>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Show this flight", @flight %> |
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= form_with url: "/flights", method: :get, local: true  do |f| %>
  <%= f.label "Departure Aiport:" %>
  <%= f.select(:departure_id, @airport_options) %>
  <br>
  <%= f.label "Arrival Aiport:" %>
  <%= f.select(:arrival_id, @airport_options) %>
  <br>
  <%= f.label "Date:" %>
  <%= select_date(Date.today) %>
  <br>
  <%= f.label "Number of Seats" %>
  <%= text_field_tag(:seats) %>
  <br>
  <br>
  <%= f.submit "Look for flights" %>
<% end %>


<br>
<br>
<% if @flights.empty? %>
  <p>No flights found.</p>
<% else %>
  <%= form_with url: "/bookings/new", method: :get, local: true  do |form| %>
    <%= form.hidden_field :seats, value: @seats %>
    <% @flights.each do |flight| %>
      <%= form.radio_button(:flight, flight.id) %>
      <%= form.label(:flight, flight.vacancy) %>
    <% end %>
    <br>
    <br>
    <%= form.submit "Book Flight" %>
  <% end %>
<% end %>

app/views/flights/new.html.erb
<% content_for :title, "New flight" %>

<h1>New flight</h1>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/flights/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flight %>

<div>
  <%= link_to "Edit this flight", edit_flight_path(@flight) %> |
  <%= link_to "Back to flights", flights_path %>

  <%= button_to "Destroy this flight", @flight, method: :delete %>
</div>