config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :passengers
  resources :flights
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "flights#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  belongs_to :passenger
  accepts_nested_attributes_for :passenger
  accepts_nested_attributes_for :flight
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    # Rails.logger.debug "Params: #{params.inspect}"
    @booking = Booking.new
    @booking.build_passenger
    @flight = Flight.find(new_booking_params["flight"].to_i)
    @booking.flight = @flight
    @seats = new_booking_params["seats"]
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)
    seats = params[:booking][:seats].to_i
    @flight = Flight.find(booking_params[:flight_id])
    Rails.logger.debug seats

    respond_to do |format|
      if @booking.save
        @booking.flight.decrement!(:vacancy, seats)
        PassengerMailer.with(passenger: @booking.passenger, flight: @flight).booking_confirmation.deliver_now
        format.html { redirect_to @booking, notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy!

    respond_to do |format|
      format.html { redirect_to bookings_path, status: :see_other, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:flight_id, passenger_attributes: [:name, :email])
    end

    def new_booking_params
      params.permit(:seats, :flight)
    end

    def passenger_attributes
      self.passenger.build(passenger_attributes)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Flight:</strong>
    <%= booking.flight_id %>
  </p>

  <p>
    <strong>Passenger:</strong>
    <%= booking.passenger_id %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :flight_id, style: "display: block" %>
    <%= form.text_field :flight_id %>
  </div>

  <div>
    <%= form.label :passenger_id, style: "display: block" %>
    <%= form.text_field :passenger_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<% content_for :title, "Editing booking" %>

<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Bookings" %>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<% content_for :title, "New booking" %>

<h1>New booking</h1>

<%= form_with model: @booking do |f| %>
  <%= f.hidden_field :seats, value: @seats %>
  <%= f.hidden_field :flight_id, value: @booking.flight_id %>
  <%= f.fields_for :passenger do |pf| %>
    <%= pf.label :name %>
    <%= pf.text_field :name %>
    <br>
    <%= pf.label :email %>
    <%= pf.text_field :email %>
  <% end %>
  <br>
  <%= f.submit "Book Now" %>
<% end %>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= @booking.flight.name %>
<br>
<%= @booking.passenger.name %>
<br>
<%= @booking.passenger.email %>
<br>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", root_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>